### ISSUE TITLE
Update examples and add to Chapel tests

### ISSUE THREAD

**Issue by bkmgit** [hpc-carpentry/hpc-chapel#20]
It would be good to update the examples to make sure they work with the latest Chapel release.  One way to ensure that they keep working is to add the examples to [Chapel's tests](https://github.com/chapel-lang/chapel/tree/main/test).

**Comment by razoumov** [comment]
Hi Benson -- thank you for the idea! I will go through all examples today and will make sure they work with 1.26.0. As for adding them to the Chapel tests, I am not sure these examples are sufficiently high-profile for that. They should mostly work, with occasional updates once every few years, which I will do now. Alex.

**Comment by bradcray** [comment]
Hi @razoumov : Just to not catch you unawares, we're wrapping up the Chapel 1.27.0 release this week, which should be available next week.  Updating a version at a time is still recommended in order to get deprecation warnings along the way, so going through 1.26.0 would still be reasonable.  Just wanted to make sure next week's release didn't catch you off-guard.

If you are interested in having automated testing of, and support for, your examples, I don't think there's any real downside to submitting them to our test system—there's no bar for profile, and what you've got is much higher profile than many of the 13,000+ tests that are there now in that it's public.  I think it probably is more a question of whether you want to put in the effort of getting them into our test system's format (which is easy for deterministic tests, harder for non-deterministic ones).  Once they're there, an advantage would be that if/when we change things that break the tests going forward, we'd be changing them to keep them working.

(We could also undertake making the exercises into tests ourselves, but it's not something I would do without getting the author's buy-in, for IP/licensing reasons.  And I don't know whether we'd get around to prioritizing it on our own).

**Comment by razoumov** [comment]
@bkmgit I updated all examples to make them compatible with Chapel 1.26, and also updated the setup information for Compute Canada clusters in one of the files.

@bradcray Thank you for the heads-up! I am teaching a full-day Chapel workshop early next week, so I thought it would be a good chance to update the website even before 1.27.0 release comes out. The examples in this repository have not been updated for quite a few years!

I think for now I will not be putting these examples into the test system, unless someone volunteers to do it.

There are quite a few things missing from these lessons, e.g. parallel I/O, especially with scientific formats such as NetCDF and HDF5, some basics of parallel linear algebra (I have not followed any recent developments in this area in Chapel), maybe something else?

**Comment by bkmgit** [comment]
@razoumov Thanks for this. Nice that this lesson is actively offered. Adding more content might be better done in a separate lesson, blocks of 4 or at most 8 hours make composing a workshop for a specific audience easier.
CC @tkphd @ocaisa @reid-a
